-- Stockroom: warehouse stock + movement ledger. Plain Postgres — authz lives
-- in the FastAPI backend, not the database. One-paste setup: run the whole
-- file against a fresh database (Neon SQL editor or psql).

create extension if not exists pgcrypto;

-- ── app-level users ────────────────────────────────────────────────────────
create schema auth;

create table auth.users (
  id uuid primary key,
  email text unique not null,
  encrypted_password text not null,
  created_at timestamptz not null default now(),
  last_sign_in_at timestamptz,
  raw_user_meta_data jsonb not null default '{}'
);

create function auth.uid() returns uuid
language sql stable
as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;

insert into auth.users (id, email, encrypted_password, last_sign_in_at) values
  ('11111111-1111-4111-8111-111111111111', 'alice@example.com',          crypt('poc-alice-1',       gen_salt('bf')), now() - interval '2 days'),
  ('91000000-0000-4000-8000-000000000001', 'stockroom+demo@example.com', crypt('stockroom-demo-1',  gen_salt('bf')), now() - interval '1 days'),
  ('91000000-0000-4000-8000-000000000002', 'floor.lee@warehouse.test',   crypt('lee-floor-1',       gen_salt('bf')), now() - interval '3 days'),
  ('91000000-0000-4000-8000-000000000003', 'floor.grant@warehouse.test', crypt('grant-floor-1',     gen_salt('bf')), now() - interval '6 days');

-- ── file storage bookkeeping (no objects yet) ──────────────────────────────
create schema storage;

create table storage.buckets (
  id text primary key,
  public boolean not null default false
);

create table storage.objects (
  id uuid primary key default gen_random_uuid(),
  bucket_id text not null references storage.buckets(id),
  name text not null,
  owner uuid references auth.users(id),
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  unique (bucket_id, name)
);

-- ── app schema ─────────────────────────────────────────────────────────────

create table public.warehouses (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  region text not null check (region in ('us-east', 'us-west', 'eu', 'apac')),
  created_at timestamptz not null default now()
);

insert into public.warehouses (code, name, region) values
  ('WH-EAST-1', 'Newark DC',    'us-east'),
  ('WH-EAST-2', 'Atlanta DC',   'us-east'),
  ('WH-WEST-1', 'Reno DC',      'us-west'),
  ('WH-EU-1',   'Rotterdam DC', 'eu'),
  ('WH-APAC-1', 'Singapore DC', 'apac');

create table public.skus (
  id bigint generated by default as identity primary key,
  sku_code text not null unique,
  name text not null,
  category text not null,
  unit_cost numeric(10, 2) not null,
  attributes jsonb not null default '{}',
  created_at timestamptz not null default now()
);

insert into public.skus (sku_code, name, category, unit_cost, attributes)
select
  'SKU-' || lpad(n::text, 5, '0'),
  (array['Shipping Box', 'Packing Tape', 'Pallet Wrap', 'Label Roll', 'Foam Insert',
         'Steel Strap', 'Cardboard Divider', 'Bubble Wrap', 'Poly Mailer', 'Wood Pallet'])[(n % 10) + 1]
    || ' - variant ' || n,
  (array['packaging', 'shipping', 'raw-material', 'consumable'])[(n % 4) + 1],
  round((1.5 + (n % 50) * 0.75)::numeric, 2),
  jsonb_build_object('weight_kg', round((0.1 + (n % 20) * 0.3)::numeric, 2)::float8, 'fragile', (n % 7 = 0))
from generate_series(1, 60) as n;

create table public.stock_levels (
  id bigint generated by default as identity primary key,
  warehouse_id bigint not null references public.warehouses(id),
  sku_id bigint not null references public.skus(id),
  quantity_on_hand int not null default 0,
  reorder_point int not null default 10,
  updated_at timestamptz not null default now(),
  unique (warehouse_id, sku_id)
);

-- sparse coverage: each warehouse stocks ~50 of the 60 skus
insert into public.stock_levels (warehouse_id, sku_id, quantity_on_hand, reorder_point, updated_at)
select w.id, s.id,
       (((w.id * 37 + s.id * 11) % 400)),
       10 + (s.id % 15),
       now() - ((s.id % 20) || ' days')::interval
from public.warehouses w
cross join public.skus s
where (w.id + s.id) % 6 != 0;

create table public.movements (
  id bigint generated by default as identity primary key,
  warehouse_id bigint not null references public.warehouses(id),
  sku_id bigint not null references public.skus(id),
  movement_type text not null check (movement_type in ('receipt', 'shipment', 'adjustment', 'transfer')),
  quantity int not null,
  recorded_by uuid references auth.users(id),
  reference_code text,
  occurred_at timestamptz not null default now()
);

insert into public.movements (warehouse_id, sku_id, movement_type, quantity, recorded_by, reference_code, occurred_at)
select
  ((n % 5) + 1),
  ((n % 60) + 1),
  (array['receipt', 'shipment', 'adjustment', 'transfer'])[(n % 4) + 1],
  case when (n % 4) = 0 then -1 * ((n % 25) + 1) else (n % 40) + 1 end,
  (array[
    '91000000-0000-4000-8000-000000000002'::uuid,
    '91000000-0000-4000-8000-000000000003'::uuid,
    '11111111-1111-4111-8111-111111111111'::uuid
  ])[(n % 3) + 1],
  'REF-' || to_char('2026-01-01'::date + (n || ' hours')::interval, 'YYYYMMDD') || '-' || n,
  '2026-01-01T00:00:00Z'::timestamptz + (n || ' hours')::interval
from generate_series(1, 1100) as n;

create view public.stock_alerts as
select w.code as warehouse_code, s.sku_code, s.name,
       sl.quantity_on_hand, sl.reorder_point
from public.stock_levels sl
join public.warehouses w on w.id = sl.warehouse_id
join public.skus s on s.id = sl.sku_id
where sl.quantity_on_hand <= sl.reorder_point;

create function public.touch_stock_level() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

create trigger stock_levels_touch before update on public.stock_levels
for each row execute function public.touch_stock_level();

select setval(pg_get_serial_sequence('public.warehouses', 'id'), 50);
select setval(pg_get_serial_sequence('public.skus', 'id'), 500);
select setval(pg_get_serial_sequence('public.stock_levels', 'id'), 1000);
select setval(pg_get_serial_sequence('public.movements', 'id'), 5000);

analyze;
